# Generated by Django 5.1.7 on 2025-04-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_delete_yn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='assembly_packaging',
            field=models.CharField(blank=True, null=True, verbose_name='Assembly/Packaging'),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_delivery',
            field=models.CharField(blank=True, null=True, verbose_name='Final Delivery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='injection_info',
            field=models.CharField(blank=True, null=True, verbose_name='Injection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='plating',
            field=models.CharField(blank=True, null=True, verbose_name='Plating'),
        ),
    ]
