# Generated by Django 5.1.7 on 2025-04-03 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_assembly_packaging_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='단가')),
                ('date', models.DateTimeField(verbose_name='일자')),
                ('created_by', models.CharField(max_length=50, verbose_name='등록자')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product.product', verbose_name='제품')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
