# Generated by Django 5.2 on 2025-04-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hanger_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='투입 행거 수'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_per_rack',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='렉당 제품 수량'),
        ),
        migrations.AddField(
            model_name='product',
            name='production_program_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='생산 프로그램 번호'),
        ),
        migrations.AddField(
            model_name='product',
            name='rack_per_hanger',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='행거 당 렉 수량'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='총 생산량'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='총 생산시간 (분)'),
        ),
        migrations.AddField(
            model_name='product',
            name='turn_time_per_hanger',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='행거당 생산 턴 시간 (분)'),
        ),
    ]
