# Generated by Django 5.2 on 2025-04-24 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0005_moldhistory'),
        ('product', '0005_product_hanger_count_product_product_per_rack_and_more'),
        ('submaterial', '0002_alter_submaterial_delete_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='injection_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='injection.injection', verbose_name='사출품'),
        ),
        migrations.AddField(
            model_name='product',
            name='submaterial_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='submaterial.submaterial', verbose_name='부자재'),
        ),
    ]
