# Generated by Django 5.2 on 2025-04-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_injection_item_product_submaterial_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='패키지 수량'),
        ),
    ]
