# Generated by Django 5.2 on 2025-04-24 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_package_quantity'),
        ('submaterial', '0002_alter_submaterial_delete_yn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubmaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='소요 수량')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_submaterials', to='product.product')),
                ('submaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submaterial.submaterial', verbose_name='부자재')),
            ],
        ),
    ]
