# Generated by Django 5.2 on 2025-11-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productsubmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packaging_spec_file',
            field=models.FileField(blank=True, null=True, upload_to='product/packaging/', verbose_name='포장사양서'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='박스당 포장 수량'),
        ),
    ]
