"""
Django settings for skerp project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qjl-2e_i2=feun@g7f%2i6=a2^e3r)*zs4^2=-h(t*!=3m84@_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'main',
    'userinfo',
    'board',
    'core',
    'master',
    'resource',
    'sales',            # 영업 -> 고객사 발주 관리  # 고객사 수주 등 영업 도메인
    'purchase',         # 구매 전반 (사출 발주 포함 가능) 구매 -> 예정
    'production',       # 생산 -> # 생산 계획/지시/실적 등 예정
    'quality',          # 품질 -> # 검사 결과, 품질 이슈 처리예정
    'lab',              # 연구실 ->  # 시험성적서, 분석 결과 등 예정
    'support',          # 경영지원 -> # 인사, 회계, 경영지원 등 예정
    'widget_tweaks',
    'vendor',           # 기초코드관리 -> 거래처
    'mastercode',       # 기초코드관리 -> 코드관리
    'equipment',        # 기초코드관리 -> 생산설비관리
    'process',          # 기초코드관리 -> 공정항목관리
    'spec',             # 기초코드관리 -> 제조사항관리
    'qualityitems',     # 기초코드관리 -> 품질관리항목관리
    'product',          # 자원 관리 -> 제품관리
    'injection',        # 자원 관리 -> 사출관리
    'chemical',         # 자원 관리 -> 약품관리
    'nonferrous',       # 자원 관리 -> 비철관리
    'submaterial',      # 자원 관리 -> 부자재관리
    'rack',             # 자원 관리 -> 랙 관리 -> 이거는 랙크관리 시스템의 역확도 같이 수행합니다.
    'injectionorder',   # 구매 -> 사출 발주
    'partnerorder',     # 협력사 -> 협력사 발주 처리
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'skerp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'skerp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'skerp_db',
        'USER': 'skerp_user',
        'PASSWORD': 'kwc8264***',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static',
]

LOGIN_REDIRECT_URL = '/dashboard/'

AUTH_USER_MODEL = 'userinfo.CustomUser'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'