# Generated by Django 5.1.7 on 2025-04-02 02:02

import django.db.models.deletion
import django.utils.timezone
import equipment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0004_alter_vendor_outsourcing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='설비명')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='설비규격')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='구입일자')),
                ('description', models.TextField(blank=True, verbose_name='설비설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to=equipment.models.equipment_image_upload_path, verbose_name='설비사진')),
                ('equipment_code', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='설비코드')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vendor', verbose_name='구입처')),
            ],
        ),
    ]
