# Generated by Django 5.1.7 on 2025-04-02 07:42

import django.db.models.deletion
import django.utils.timezone
import process.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='공정명')),
                ('description', models.TextField(blank=True, verbose_name='공정설명')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=process.models.process_file_upload_path, verbose_name='작업표준서 파일')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('created_by', models.CharField(max_length=50, verbose_name='등록자')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일시')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='process.process', verbose_name='공정')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
