# Generated by Django 5.2 on 2025-11-13 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0004_chemical_msds_file_chemical_tds_file_and_more'),
        ('equipment', '0002_equipmenthistory'),
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='표시순서')),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chemical.chemical', verbose_name='약품')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.process', verbose_name='공정')),
            ],
            options={
                'verbose_name': '공정별 약품',
                'verbose_name_plural': '공정별 약품',
                'ordering': ['process', 'order', 'id'],
                'unique_together': {('process', 'chemical')},
            },
        ),
        migrations.AddField(
            model_name='process',
            name='chemicals',
            field=models.ManyToManyField(blank=True, related_name='processes', through='process.ProcessChemical', to='chemical.chemical', verbose_name='사용 약품'),
        ),
        migrations.CreateModel(
            name='ProcessEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='표시순서')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment', verbose_name='설비')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.process', verbose_name='공정')),
            ],
            options={
                'verbose_name': '공정별 설비',
                'verbose_name_plural': '공정별 설비',
                'ordering': ['process', 'order', 'id'],
                'unique_together': {('process', 'equipment')},
            },
        ),
        migrations.AddField(
            model_name='process',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='processes', through='process.ProcessEquipment', to='equipment.equipment', verbose_name='사용 설비'),
        ),
    ]
