# Generated by Django 5.2 on 2025-11-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_processchemical_process_chemicals_processequipment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['display_order', 'id'], 'verbose_name': '공정', 'verbose_name_plural': '공정'},
        ),
        migrations.AddField(
            model_name='process',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=1, help_text='공정 목록에서의 표시 순번', verbose_name='표시순번'),
        ),
    ]
