# Generated by Django 5.2 on 2025-11-18 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonferrous', '0001_initial'),
        ('process', '0003_alter_process_options_process_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessNonFerrous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='표시순서')),
                ('nonferrous', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nonferrous.chemical', verbose_name='비철')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.process', verbose_name='공정')),
            ],
            options={
                'verbose_name': '공정별 비철',
                'verbose_name_plural': '공정별 비철',
                'ordering': ['process', 'order', 'id'],
                'unique_together': {('process', 'nonferrous')},
            },
        ),
        migrations.AddField(
            model_name='process',
            name='nonferrous',
            field=models.ManyToManyField(blank=True, related_name='processes', through='process.ProcessNonFerrous', to='nonferrous.chemical', verbose_name='사용 비철'),
        ),
    ]
