# Generated by Django 5.2 on 2025-09-05 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_productsubmaterial'),
        ('vendor', '0006_vendor_address_vendor_can_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_lot', models.CharField(editable=False, max_length=20, unique=True, verbose_name='작업 LOT')),
                ('order_qty', models.PositiveIntegerField(verbose_name='지시 수량(EA)')),
                ('status', models.CharField(choices=[('대기', '대기'), ('진행중', '진행중'), ('생산완료', '생산완료')], default='대기', max_length=10)),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='계획 시작')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='계획 종료')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='실 시작')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='실 종료')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='vendor.vendor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='product.product')),
            ],
            options={
                'verbose_name': '작업지시서',
                'verbose_name_plural': '작업지시서',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='1렉당 수용량(EA)')),
                ('rack_count', models.PositiveIntegerField(default=0, verbose_name='렉 수')),
                ('hanger_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='1행거당 렉 수')),
                ('hanger_count', models.PositiveIntegerField(default=0, verbose_name='행거 수')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='작업 순서')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.workorder')),
            ],
            options={
                'verbose_name': '작업지시서 상세',
                'verbose_name_plural': '작업지시서 상세',
                'ordering': ['work_order', 'sequence'],
            },
        ),
    ]
