# Generated by Django 5.2 on 2025-09-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='dlt_yn',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], db_index=True, default='N', max_length=1, verbose_name='삭제 여부'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='사용 여부'),
        ),
    ]
