# Generated by Django 5.2 on 2025-11-12 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_workorderline_dlt_yn_workorderline_is_active'),
        ('purchase', '0017_unifiedreceipt_certificate_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderInjectionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_qty', models.PositiveIntegerField(default=0, verbose_name='투입 수량')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workorder_usages', to='purchase.injectionreceiptline', verbose_name='사출 입고 라인')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injection_usages', to='production.workorder', verbose_name='작업지시')),
            ],
            options={
                'db_table': 'production_workorder_injection_usage',
                'unique_together': {('workorder', 'line')},
            },
        ),
    ]
