# Generated by Django 5.2 on 2025-11-14 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_alter_process_options_process_display_order'),
        ('production', '0004_workorderinjectionusage'),
        ('vendor', '0007_vendoritemkind_vendor_major_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='사용 여부')),
                ('dlt_yn', models.CharField(choices=[('N', 'N'), ('Y', 'Y')], db_index=True, default='N', max_length=1, verbose_name='삭제 여부')),
                ('name', models.CharField(max_length=100, verbose_name='품명')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='규격')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='비고')),
                ('current_qty', models.IntegerField(default=0, verbose_name='현재 수량')),
                ('last_in_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 입고일시')),
                ('last_out_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 사용일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '스페어파트',
                'verbose_name_plural': '스페어파트',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SparePartReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(verbose_name='입고일시')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='입고 수량')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='production.sparepart', verbose_name='스페어파트')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spare_part_receipts', to='vendor.vendor', verbose_name='거래처')),
            ],
            options={
                'verbose_name': '스페어파트 입고',
                'verbose_name_plural': '스페어파트 입고',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SparePartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(verbose_name='사용일시')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='사용 수량')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spare_part_usages', to='process.process', verbose_name='사용공정')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='production.sparepart', verbose_name='스페어파트')),
            ],
            options={
                'verbose_name': '스페어파트 사용',
                'verbose_name_plural': '스페어파트 사용',
                'ordering': ['-used_at', '-id'],
            },
        ),
    ]
