# Generated by Django 5.2 on 2025-11-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_sparepart_sparepartreceipt_sparepartusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepartreceipt',
            name='note',
        ),
        migrations.AddField(
            model_name='sparepartreceipt',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='금액'),
        ),
    ]
