# Generated by Django 5.2 on 2025-11-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_remove_sparepartreceipt_note_sparepartreceipt_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sparepartusage',
            options={'ordering': ['-used_at', '-id'], 'verbose_name': '스페어파트 사용'},
        ),
        migrations.AddField(
            model_name='sparepart',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='모델명'),
        ),
    ]
