# Generated by Django 5.2 on 2025-11-14 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0004_chemical_msds_file_chemical_tds_file_and_more'),
        ('equipment', '0002_equipmenthistory'),
        ('process', '0003_alter_process_options_process_display_order'),
        ('production', '0007_alter_sparepartusage_options_sparepart_model_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='사용 여부')),
                ('dlt_yn', models.CharField(choices=[('N', 'N'), ('Y', 'Y')], db_index=True, default='N', max_length=1, verbose_name='삭제 여부')),
                ('work_date', models.DateField(verbose_name='투입 일자')),
                ('shift', models.CharField(choices=[('DAY', '주간'), ('NIGHT', '야간')], default='DAY', max_length=10, verbose_name='근무조')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemical_additions', to='process.process', verbose_name='공정')),
            ],
            options={
                'verbose_name': '약품 투입 헤더',
                'verbose_name_plural': '약품 투입 헤더',
                'db_table': 'production_chemical_addition',
                'ordering': ['-work_date', '-id'],
                'unique_together': {('process', 'work_date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='ChemicalAdditionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='투입량')),
                ('unit', models.CharField(default='ml', max_length=10, verbose_name='단위')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('addition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.chemicaladdition', verbose_name='투입헤더')),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemical_addition_lines', to='chemical.chemical', verbose_name='약품')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemical_addition_lines', to='equipment.equipment', verbose_name='투입설비')),
            ],
            options={
                'verbose_name': '약품 투입 상세',
                'verbose_name_plural': '약품 투입 상세',
                'db_table': 'production_chemical_addition_line',
                'ordering': ['addition_id', 'id'],
            },
        ),
    ]
