# Generated by Django 5.2 on 2025-11-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_chemicaladdition_chemicaladditionline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicaladditionline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='투입량'),
        ),
    ]
