# Generated by Django 5.2 on 2025-11-18 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonferrous', '0001_initial'),
        ('process', '0004_processnonferrous_process_nonferrous'),
        ('production', '0010_alter_chemicaladditionline_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonFerrousAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='사용 여부')),
                ('dlt_yn', models.CharField(choices=[('N', 'N'), ('Y', 'Y')], db_index=True, default='N', max_length=1, verbose_name='삭제 여부')),
                ('work_date', models.DateField(verbose_name='투입 일자')),
                ('shift', models.CharField(choices=[('DAY', '주간'), ('NIGHT', '야간')], default='DAY', max_length=10, verbose_name='근무조')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nonferrous_additions', to='process.process', verbose_name='공정')),
            ],
            options={
                'verbose_name': '비철 투입 헤더',
                'verbose_name_plural': '비철 투입 헤더',
                'db_table': 'production_nonferrous_addition',
                'ordering': ['-work_date', '-id'],
                'unique_together': {('process', 'work_date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='NonFerrousAdditionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(blank=True, help_text='향후 욕조/라인 구분용, 현재는 미사용', max_length=20, null=True, verbose_name='그룹코드')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='투입량')),
                ('unit', models.CharField(default='kg', max_length=10, verbose_name='단위')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('addition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.nonferrousaddition', verbose_name='비철 투입 헤더')),
                ('nonferrous', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nonferrous.chemical', verbose_name='비철')),
            ],
            options={
                'verbose_name': '비철 투입 상세',
                'verbose_name_plural': '비철 투입 상세',
                'db_table': 'production_nonferrous_addition_line',
                'ordering': ['addition_id', 'id'],
            },
        ),
    ]
