# Generated by Django 5.2 on 2025-09-02 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('injectionorder', '0002_alter_injectionorder_options_and_more'),
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_lot', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField()),
                ('qty', models.PositiveIntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order_lot_snapshot', models.CharField(blank=True, max_length=40)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='injectionorder.injectionorder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.warehouse')),
            ],
            options={
                'db_table': 'purchase_injectionreceipt',
                'indexes': [models.Index(fields=['date', 'receipt_lot'], name='purchase_in_date_bbb8a4_idx'), models.Index(fields=['is_active', 'is_deleted'], name='purchase_in_is_acti_0c6302_idx')],
            },
        ),
    ]
