# Generated by Django 5.2 on 2025-09-04 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injectionorder', '0002_alter_injectionorder_options_and_more'),
        ('master', '0001_initial'),
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_lot', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField()),
                ('qty', models.PositiveIntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_used_at_issue', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'purchase_injectionissue',
            },
        ),
        migrations.AddField(
            model_name='injectionreceipt',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='injectionreceipt',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='injectionreceipt',
            index=models.Index(fields=['is_used', 'warehouse'], name='purchase_in_is_used_089332_idx'),
        ),
        migrations.AddIndex(
            model_name='injectionreceipt',
            index=models.Index(fields=['order'], name='purchase_in_order_i_39f996_idx'),
        ),
        migrations.AddConstraint(
            model_name='injectionreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='injrec_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='injectionreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('is_used', True), ('used_at__isnull', True), _connector='OR'), name='injrec_used_time_consistent'),
        ),
        migrations.AddField(
            model_name='injectionissue',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='injectionissue',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_from', to='master.warehouse'),
        ),
        migrations.AddField(
            model_name='injectionissue',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='purchase.injectionreceipt'),
        ),
        migrations.AddField(
            model_name='injectionissue',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_to', to='master.warehouse'),
        ),
        migrations.AddIndex(
            model_name='injectionissue',
            index=models.Index(fields=['date', 'receipt_lot'], name='purchase_in_date_15786e_idx'),
        ),
        migrations.AddIndex(
            model_name='injectionissue',
            index=models.Index(fields=['from_warehouse', 'to_warehouse'], name='purchase_in_from_wa_fc1150_idx'),
        ),
        migrations.AddIndex(
            model_name='injectionissue',
            index=models.Index(fields=['receipt'], name='purchase_in_receipt_f60d6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='injectionissue',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='injissue_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='injectionissue',
            constraint=models.CheckConstraint(condition=models.Q(('from_warehouse', models.F('to_warehouse')), _negated=True), name='injissue_diff_wh'),
        ),
    ]
