# Generated by Django 5.2 on 2025-09-13 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('injectionorder', '0005_alter_injectionorder_flow_status_injectionreceipt'),
        ('master', '0001_initial'),
        ('purchase', '0002_injectionissue_injectionreceipt_is_used_and_more'),
        ('vendor', '0006_vendor_address_vendor_can_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_lot', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField()),
                ('qty', models.PositiveIntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('CHEM', '약품'), ('NF', '비철'), ('SUP', '부자재')], db_index=True, max_length=8)),
                ('is_used_at_issue', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'purchase_issue',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_lot', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField()),
                ('qty', models.PositiveIntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('CHEM', '약품'), ('NF', '비철'), ('SUP', '부자재')], db_index=True, max_length=8)),
                ('item_id', models.PositiveBigIntegerField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('item_name_snapshot', models.CharField(max_length=200)),
                ('spec_snapshot', models.CharField(blank=True, max_length=200)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'purchase_receipt',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='injectionissue',
            constraint=models.UniqueConstraint(fields=('receipt_lot',), name='uniq_injectionissue_receipt_lot'),
        ),
        migrations.AddConstraint(
            model_name='injectionreceipt',
            constraint=models.UniqueConstraint(fields=('receipt_lot',), name='uniq_injectionreceipt_receipt_lot'),
        ),
        migrations.AddField(
            model_name='unifiedissue',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unifiedissue',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unified_issues_from', to='master.warehouse'),
        ),
        migrations.AddField(
            model_name='unifiedissue',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unified_issues_to', to='master.warehouse'),
        ),
        migrations.AddField(
            model_name='unifiedreceipt',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unifiedreceipt',
            name='item_ct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='unifiedreceipt',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unified_receipts', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='unifiedreceipt',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unified_receipts', to='master.warehouse'),
        ),
        migrations.AddField(
            model_name='unifiedissue',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='purchase.unifiedreceipt'),
        ),
        migrations.AddIndex(
            model_name='unifiedreceipt',
            index=models.Index(fields=['category', 'date'], name='purchase_re_categor_b00e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedreceipt',
            index=models.Index(fields=['category', 'warehouse'], name='purchase_re_categor_6371e2_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedreceipt',
            index=models.Index(fields=['category', 'vendor'], name='purchase_re_categor_71a831_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedreceipt',
            index=models.Index(fields=['item_ct', 'item_id'], name='purchase_re_item_ct_fabd7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='unifiedreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='unirec_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='unifiedreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('is_used', True), ('used_at__isnull', True), _connector='OR'), name='unirec_used_time_consistent'),
        ),
        migrations.AddConstraint(
            model_name='unifiedreceipt',
            constraint=models.UniqueConstraint(fields=('receipt_lot',), name='uniq_unifiedreceipt_receipt_lot'),
        ),
        migrations.AddIndex(
            model_name='unifiedissue',
            index=models.Index(fields=['category', 'date'], name='purchase_is_categor_ab1e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedissue',
            index=models.Index(fields=['from_warehouse', 'to_warehouse'], name='purchase_is_from_wa_db42f4_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedissue',
            index=models.Index(fields=['receipt'], name='purchase_is_receipt_02f998_idx'),
        ),
        migrations.AddConstraint(
            model_name='unifiedissue',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='uniissue_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='unifiedissue',
            constraint=models.CheckConstraint(condition=models.Q(('from_warehouse', models.F('to_warehouse')), _negated=True), name='uniissue_diff_wh'),
        ),
        migrations.AddConstraint(
            model_name='unifiedissue',
            constraint=models.UniqueConstraint(fields=('receipt_lot',), name='uniq_unifiedissue_receipt_lot'),
        ),
    ]
