# Generated by Django 5.2 on 2025-09-13 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('purchase', '0003_unifiedissue_unifiedreceipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_lot', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField()),
                ('qty', models.PositiveIntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('CHEM', '약품'), ('NF', '비철'), ('SUP', '부자재')], db_index=True, max_length=8)),
                ('reason_code', models.CharField(blank=True, max_length=40)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unified_returns_from', to='master.warehouse')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchase.unifiedreceipt')),
            ],
            options={
                'db_table': 'purchase_return',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['category', 'date'], name='purchase_re_categor_b03b9f_idx'), models.Index(fields=['from_warehouse'], name='purchase_re_from_wa_09c902_idx'), models.Index(fields=['receipt'], name='purchase_re_receipt_575a57_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='unireturn_qty_positive'), models.UniqueConstraint(fields=('receipt_lot',), name='uniq_unifiedreturn_receipt_lot')],
            },
        ),
    ]
