# Generated by Django 5.2 on 2025-09-13 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('purchase', '0004_unifiedreturn'),
        ('vendor', '0006_vendor_address_vendor_can_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CHEM', '약품'), ('NF', '비철'), ('SUP', '부자재')], db_index=True, max_length=8)),
                ('order_lot', models.CharField(db_index=True, max_length=20, unique=True)),
                ('order_date', models.DateField(db_index=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order_status', models.CharField(choices=[('NEW', '발주'), ('CNL', '취소')], db_index=True, default='NEW', max_length=3)),
                ('flow_status', models.CharField(choices=[('NG', '미입고'), ('PRT', '부분입고'), ('RCV', '입고완료')], db_index=True, default='NG', max_length=3)),
                ('cancel_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cancel_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_unified_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unified_orders_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified_orders_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unified_orders', to='vendor.vendor')),
            ],
            options={
                'db_table': 'purchase_order',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveBigIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('item_name_snapshot', models.CharField(max_length=200)),
                ('spec_snapshot', models.CharField(blank=True, max_length=200)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('item_ct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.unifiedorder')),
            ],
            options={
                'db_table': 'purchase_order_item',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='unifiedorder',
            index=models.Index(fields=['category', 'order_date'], name='purchase_or_categor_46c77f_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedorder',
            index=models.Index(fields=['category', 'vendor'], name='purchase_or_categor_1bb4da_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedorder',
            index=models.Index(fields=['order_status'], name='purchase_or_order_s_7738fa_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedorder',
            index=models.Index(fields=['flow_status'], name='purchase_or_flow_st_bde864_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedorderitem',
            index=models.Index(fields=['order'], name='purchase_or_order_i_44de2a_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedorderitem',
            index=models.Index(fields=['item_ct', 'item_id'], name='purchase_or_item_ct_728865_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedorderitem',
            index=models.Index(fields=['expected_date'], name='purchase_or_expecte_6294ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='unifiedorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='uniorderitem_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='unifiedorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='uniorderitem_unit_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='unifiedorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='uniorderitem_amount_nonneg'),
        ),
    ]
