# Generated by Django 5.2 on 2025-09-30 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_unifiedorder_unifiedorderitem_and_more'),
        ('quality', '0003_incominginspectiondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='입고 수량')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_line', to='quality.incominginspectiondetail', verbose_name='검사 라인(PASS)')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchase.injectionreceipt', verbose_name='입고 헤더')),
            ],
            options={
                'verbose_name': '사출 입고 라인',
                'verbose_name_plural': '사출 입고 라인',
                'indexes': [models.Index(fields=['receipt'], name='purchase_in_receipt_a5badc_idx'), models.Index(fields=['detail'], name='purchase_in_detail__d4652c_idx')],
            },
        ),
    ]
