# Generated by Django 5.2 on 2025-10-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_injectionreceiptline'),
        ('quality', '0003_incominginspectiondetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectionreceiptline',
            name='sub_lot',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='injectionreceiptline',
            name='sub_seq',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='injectionreceiptline',
            index=models.Index(fields=['sub_lot'], name='purchase_in_sub_lot_0fd4ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='injectionreceiptline',
            constraint=models.UniqueConstraint(fields=('receipt', 'sub_seq'), name='uniq_injrec_line_seq_per_receipt'),
        ),
        migrations.AddConstraint(
            model_name='injectionreceiptline',
            constraint=models.UniqueConstraint(fields=('receipt', 'sub_lot'), name='uniq_injrec_line_sublot_per_receipt'),
        ),
        migrations.AddConstraint(
            model_name='injectionreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='injrec_line_qty_positive'),
        ),
        migrations.AlterModelTable(
            name='injectionreceiptline',
            table='purchase_injectionreceiptline',
        ),
    ]
