# Generated by Django 5.2 on 2025-10-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_injectionreceiptline_sub_lot_and_more'),
        ('quality', '0003_incominginspectiondetail'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='injectionreceiptline',
            name='uniq_injrec_line_seq_per_receipt',
        ),
        migrations.RemoveConstraint(
            model_name='injectionreceiptline',
            name='uniq_injrec_line_sublot_per_receipt',
        ),
        migrations.AlterField(
            model_name='injectionreceiptline',
            name='sub_seq',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='injectionreceiptline',
            constraint=models.UniqueConstraint(condition=models.Q(('sub_seq__isnull', False)), fields=('receipt', 'sub_seq'), name='uniq_injrec_line_seq_per_receipt'),
        ),
        migrations.AddConstraint(
            model_name='injectionreceiptline',
            constraint=models.UniqueConstraint(condition=models.Q(('sub_lot__isnull', False)), fields=('receipt', 'sub_lot'), name='uniq_injrec_line_sublot_per_receipt'),
        ),
    ]
