# Generated by Django 5.2 on 2025-10-18 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injectionorder', '0005_alter_injectionorder_flow_status_injectionreceipt'),
        ('master', '0001_initial'),
        ('partnerorder', '0002_partnershipmentline'),
        ('purchase', '0008_remove_injectionreceiptline_uniq_injrec_line_seq_per_receipt_and_more'),
        ('quality', '0003_incominginspectiondetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ※ ProductionLotCounter 생성 제거 (unmanaged 테이블)
        migrations.RemoveConstraint(
            model_name='injectionreceiptline',
            name='uniq_injrec_line_seq_per_receipt',
        ),
        migrations.RemoveConstraint(
            model_name='injectionreceiptline',
            name='uniq_injrec_line_sublot_per_receipt',
        ),
        migrations.AddField(
            model_name='injectionreceipt',
            name='shipment_group',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='injection_receipts',
                to='partnerorder.partnershipmentgroup'
            ),
        ),
        migrations.AlterField(
            model_name='injectionreceiptline',
            name='sub_lot',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='injectionreceiptline',
            name='sub_seq',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='injectionreceipt',
            index=models.Index(fields=['shipment_group'], name='purchase_in_shipmen_8426b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='injectionreceiptline',
            constraint=models.UniqueConstraint(
                fields=('receipt', 'sub_seq'),
                name='uniq_injrec_line_seq_per_receipt'
            ),
        ),
    ]