# Generated by Django 5.2 on 2025-10-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_add_shipment_group_and_relax_sub_fields'),
    ]

    operations = [
    ]
