# Generated by Django 5.2 on 2025-10-18 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerorder', '0002_partnershipmentline'),
        ('purchase', '0011_enforce_notnull_and_uniques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injectionreceipt',
            name='shipment_group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='injection_receipts',
                to='partnerorder.partnershipmentgroup',
            ),
        ),
        migrations.AlterField(
            model_name='injectionreceiptline',
            name='sub_lot',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='injectionreceiptline',
            name='sub_seq',
            field=models.PositiveIntegerField(),
        ),
    ]