# Generated by Django 5.2 on 2025-10-27 13:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('master', '0001_initial'),
        ('purchase', '0013_add_line_wh_po_and_issue_line_batch'),
        ('quality', '0003_incominginspectiondetail'),
        ('vendor', '0007_vendoritemkind_vendor_major_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLotCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_type', models.TextField()),
                ('lot_date', models.DateField()),
                ('last_seq', models.IntegerField()),
            ],
            options={
                'db_table': 'production_lot_counter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InjectionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('consume', '소비'), ('return', '반납'), ('adjust', '조정')], db_index=True, default='consume', max_length=10)),
                ('qty_change', models.IntegerField(help_text='소비는 +, 반납은 -, 조정은 ± (0 불가)')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ref_type', models.CharField(blank=True, max_length=30)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('transaction_uid', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'purchase_injectionusage',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('consume', '소비'), ('return', '반납'), ('adjust', '조정')], db_index=True, default='consume', max_length=10)),
                ('qty_change', models.IntegerField(help_text='소비는 +, 반납은 -, 조정은 ± (0 불가)')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ref_type', models.CharField(blank=True, max_length=30)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('transaction_uid', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'purchase_unifiedusage',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='injectionreceiptline',
            name='purchase_in_sub_lot_0fd4ea_idx',
        ),
        migrations.RenameIndex(
            model_name='injectionreceiptline',
            new_name='purchase_in_po_lot_90a1f6_idx',
            old_name='injrec_line_polot_part_idx',
        ),
        migrations.AddField(
            model_name='injectionreceiptline',
            name='use_status',
            field=models.CharField(choices=[('미사용', '미사용'), ('부분사용', '부분사용'), ('사용완료', '사용완료')], db_index=True, default='미사용', max_length=10),
        ),
        migrations.AddField(
            model_name='injectionreceiptline',
            name='used_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unifiedreceipt',
            name='use_status',
            field=models.CharField(choices=[('미사용', '미사용'), ('부분사용', '부분사용'), ('사용완료', '사용완료')], db_index=True, default='미사용', max_length=10),
        ),
        migrations.AddField(
            model_name='unifiedreceipt',
            name='used_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='injectionissue',
            name='receipt_lot',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='injectionreceipt',
            name='receipt_lot',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='unifiedissue',
            name='receipt_lot',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='unifiedorder',
            name='order_lot',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='unifiedreceipt',
            name='receipt_lot',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='unifiedreturn',
            name='receipt_lot',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='injectionissue',
            index=models.Index(fields=['receipt_line'], name='purchase_in_receipt_3e27e1_idx'),
        ),
        migrations.AddIndex(
            model_name='injectionissue',
            index=models.Index(fields=['batch_id'], name='purchase_in_batch_i_f18218_idx'),
        ),
        migrations.AddIndex(
            model_name='injectionreceiptline',
            index=models.Index(fields=['warehouse'], name='purchase_in_warehou_3e6795_idx'),
        ),
        migrations.AddIndex(
            model_name='injectionreceiptline',
            index=models.Index(fields=['use_status'], name='purchase_in_use_sta_72ae95_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedreceipt',
            index=models.Index(fields=['use_status'], name='purchase_re_use_sta_3d4bc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='injectionreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('used_qty__gte', 0)), name='inj_used_qty_ge_0'),
        ),
        migrations.AddConstraint(
            model_name='injectionreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('used_qty__lte', models.F('qty'))), name='inj_used_qty_le_qty'),
        ),
        migrations.AddConstraint(
            model_name='unifiedreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('used_qty__gte', 0)), name='unirec_used_qty_ge_0'),
        ),
        migrations.AddConstraint(
            model_name='unifiedreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('used_qty__lte', models.F('qty'))), name='unirec_used_qty_le_qty'),
        ),
        migrations.AddField(
            model_name='injectionusage',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='purchase.injectionreceiptline', verbose_name='사출 입고 라인'),
        ),
        migrations.AddField(
            model_name='injectionusage',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='injection_usages', to=settings.AUTH_USER_MODEL, verbose_name='처리자'),
        ),
        migrations.AddField(
            model_name='unifiedusage',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='purchase.unifiedreceipt', verbose_name='입고 전표(통합)'),
        ),
        migrations.AddField(
            model_name='unifiedusage',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unified_usages', to=settings.AUTH_USER_MODEL, verbose_name='처리자'),
        ),
        migrations.AddIndex(
            model_name='injectionusage',
            index=models.Index(fields=['line', 'occurred_at'], name='injusage_line_time_idx'),
        ),
        migrations.AddIndex(
            model_name='injectionusage',
            index=models.Index(fields=['action'], name='injusage_action_idx'),
        ),
        migrations.AddIndex(
            model_name='injectionusage',
            index=models.Index(fields=['ref_type', 'ref_id'], name='injusage_ref_idx'),
        ),
        migrations.AddConstraint(
            model_name='injectionusage',
            constraint=models.CheckConstraint(condition=models.Q(('qty_change', 0), _negated=True), name='injusage_qty_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='injectionusage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'consume'), ('qty_change__gt', 0)), models.Q(('action', 'return'), ('qty_change__lt', 0)), models.Q(('action', 'adjust'), models.Q(('qty_change', 0), _negated=True)), _connector='OR'), name='injusage_sign_consistency'),
        ),
        migrations.AddIndex(
            model_name='unifiedusage',
            index=models.Index(fields=['receipt', 'occurred_at'], name='uniusage_receipt_time_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedusage',
            index=models.Index(fields=['action'], name='uniusage_action_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedusage',
            index=models.Index(fields=['ref_type', 'ref_id'], name='uniusage_ref_idx'),
        ),
        migrations.AddConstraint(
            model_name='unifiedusage',
            constraint=models.CheckConstraint(condition=models.Q(('qty_change', 0), _negated=True), name='uniusage_qty_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='unifiedusage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'consume'), ('qty_change__gt', 0)), models.Q(('action', 'return'), ('qty_change__lt', 0)), models.Q(('action', 'adjust'), models.Q(('qty_change', 0), _negated=True)), _connector='OR'), name='uniusage_sign_consistency'),
        ),
    ]
