# Generated by Django 5.2 on 2025-11-03 10:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('purchase', '0015_backfill_usage_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_seq', models.PositiveIntegerField()),
                ('sub_lot', models.CharField(max_length=32, unique=True)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=18)),
                ('used_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('use_status', models.CharField(choices=[('미사용', '미사용'), ('부분사용', '부분사용'), ('사용완료', '사용완료')], db_index=True, default='미사용', max_length=10)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'purchase_unifiedreceiptline',
                'ordering': ['receipt_id', 'sub_seq'],
            },
        ),
        migrations.AlterModelOptions(
            name='injectionreceiptline',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='unifiedreceipt',
            name='unirec_used_qty_le_qty',
        ),
        migrations.AlterField(
            model_name='unifiedreceipt',
            name='used_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='unifiedusage',
            name='qty_change',
            field=models.DecimalField(decimal_places=3, help_text='소비는 +, 반납은 -, 조정은 ± (0 불가)', max_digits=18),
        ),
        migrations.AddField(
            model_name='unifiedreceiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchase.unifiedreceipt'),
        ),
        migrations.AddField(
            model_name='unifiedreceiptline',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unified_receipt_lines', to='master.warehouse'),
        ),
        migrations.AddField(
            model_name='unifiedusage',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='purchase.unifiedreceiptline'),
        ),
        migrations.AddIndex(
            model_name='unifiedusage',
            index=models.Index(fields=['receipt', 'line'], name='purchase_un_receipt_0f252c_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedreceiptline',
            index=models.Index(fields=['receipt'], name='purchase_un_receipt_9707d1_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedreceiptline',
            index=models.Index(fields=['warehouse'], name='purchase_un_warehou_0acea3_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedreceiptline',
            index=models.Index(fields=['use_status'], name='purchase_un_use_sta_cf3537_idx'),
        ),
        migrations.AddConstraint(
            model_name='unifiedreceiptline',
            constraint=models.UniqueConstraint(fields=('receipt', 'sub_seq'), name='uniq_unirec_line_seq_per_receipt'),
        ),
        migrations.AddConstraint(
            model_name='unifiedreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='unirec_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='unifiedreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('used_qty__gte', 0)), name='unirec_line_used_ge_0'),
        ),
        migrations.AddConstraint(
            model_name='unifiedreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('used_qty__lte', models.F('qty'))), name='unirec_line_used_le_qty'),
        ),
    ]
