# Generated by Django 5.2 on 2025-11-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_add_chem_sub_lot_and_usage_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedreceipt',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='purchase/receipts/certificates/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='unifiedreceiptline',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
