# Generated by Django 5.1.7 on 2025-03-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_number', models.CharField(max_length=20, verbose_name='사업자번호')),
                ('name', models.CharField(max_length=100, verbose_name='기업명')),
                ('ceo_name', models.CharField(max_length=50, verbose_name='대표자 이름')),
                ('biz_type', models.CharField(max_length=100, verbose_name='업태')),
                ('biz_item', models.CharField(max_length=100, verbose_name='업종')),
                ('address', models.TextField(verbose_name='주소')),
                ('phone', models.CharField(max_length=20, verbose_name='대표 전화번호')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='대표 팩스번호')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='대표 이메일')),
                ('tax_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='세금계산서 이메일')),
            ],
        ),
    ]
