# Generated by Django 5.1.7 on 2025-03-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_number', models.CharField(max_length=20, verbose_name='사업자번호')),
                ('name', models.CharField(max_length=100, verbose_name='기업명')),
                ('ceo_name', models.CharField(max_length=50, verbose_name='대표자 이름')),
                ('biz_type', models.CharField(max_length=100, verbose_name='업태')),
                ('biz_item', models.CharField(max_length=100, verbose_name='업종')),
                ('address', models.TextField(verbose_name='주소')),
                ('phone', models.CharField(max_length=20, verbose_name='대표 전화번호')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='대표 팩스번호')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='대표 이메일')),
                ('tax_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='세금계산서 이메일')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_id', models.CharField(max_length=20, unique=True, verbose_name='창고 ID')),
                ('name', models.CharField(max_length=100, verbose_name='창고명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='창고 설명')),
                ('is_active', models.CharField(choices=[('Y', '사용'), ('N', '미사용')], default='Y', max_length=1, verbose_name='사용여부')),
                ('is_deleted', models.CharField(choices=[('N', '정상'), ('Y', '삭제')], default='N', max_length=1, verbose_name='삭제여부')),
            ],
        ),
    ]
