# Generated by Django 5.2 on 2025-04-16 10:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('injection', '0005_moldhistory'),
        ('vendor', '0005_alter_vendor_outsourcing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_lot', models.CharField(max_length=20, unique=True, verbose_name='발주 LOT')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='발주일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dlt_yn', models.CharField(choices=[('N', '정상'), ('Y', '삭제')], default='N', max_length=1)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendor.vendor', verbose_name='발주처')),
            ],
        ),
        migrations.CreateModel(
            name='InjectionOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='발주 수량')),
                ('expected_date', models.DateField(verbose_name='입고 예정일')),
                ('unit_price', models.PositiveIntegerField(verbose_name='단가')),
                ('total_price', models.PositiveIntegerField(verbose_name='합계금액')),
                ('injection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='injection.injection', verbose_name='사출품')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='injectionorder.injectionorder')),
            ],
        ),
    ]
