# Generated by Django 5.2 on 2025-08-13 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0005_moldhistory'),
        ('injectionorder', '0001_initial'),
        ('vendor', '0006_vendor_address_vendor_can_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='injectionorder',
            options={'verbose_name': '사출 발주', 'verbose_name_plural': '사출 발주'},
        ),
        migrations.AlterModelOptions(
            name='injectionorderitem',
            options={'verbose_name': '사출 발주 품목', 'verbose_name_plural': '사출 발주 품목'},
        ),
        migrations.AddField(
            model_name='injectionorder',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='입고 예정일(헤더)'),
        ),
        migrations.AddField(
            model_name='injectionorder',
            name='shipping_registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='배송등록 시각'),
        ),
        migrations.AddField(
            model_name='injectionorder',
            name='status',
            field=models.CharField(choices=[('미입고', '미입고'), ('입고대기', '입고대기'), ('입고완료', '입고완료'), ('반출', '반출')], db_index=True, default='미입고', max_length=10, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='injectionorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='injectionorder',
            name='dlt_yn',
            field=models.CharField(choices=[('N', '정상'), ('Y', '삭제')], default='N', max_length=1, verbose_name='삭제여부'),
        ),
        migrations.AlterField(
            model_name='injectionorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='injectionorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='injectionorder.injectionorder', verbose_name='발주'),
        ),
        migrations.AddIndex(
            model_name='injectionorder',
            index=models.Index(fields=['vendor', 'status'], name='injord_vendor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='injectionorder',
            index=models.Index(fields=['order_date'], name='injord_orderdate_idx'),
        ),
        migrations.AddIndex(
            model_name='injectionorderitem',
            index=models.Index(fields=['order'], name='injitem_order_idx'),
        ),
        migrations.AddIndex(
            model_name='injectionorderitem',
            index=models.Index(fields=['expected_date'], name='injitem_expected_idx'),
        ),
    ]
