# Generated by Django 5.2 on 2025-09-12 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0005_moldhistory'),
        ('injectionorder', '0003_injectionorder_created_by_injectionorder_updated_by_and_more'),
        ('vendor', '0006_vendor_address_vendor_can_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='injectionorder',
            name='injord_vendor_status_idx',
        ),
        migrations.RemoveField(
            model_name='injectionorder',
            name='status',
        ),
        migrations.AddField(
            model_name='injectionorder',
            name='cancel_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='취소일시'),
        ),
        migrations.AddField(
            model_name='injectionorder',
            name='cancel_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_injection_orders', to=settings.AUTH_USER_MODEL, verbose_name='취소자'),
        ),
        migrations.AddField(
            model_name='injectionorder',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='취소사유'),
        ),
        migrations.AddField(
            model_name='injectionorder',
            name='flow_status',
            field=models.CharField(choices=[('NG', '미입고'), ('RDY', '입고대기'), ('RCV', '입고완료'), ('RET', '반출')], db_index=True, default='NG', help_text='미입고/입고대기/입고완료/반출', max_length=3, verbose_name='진행상태'),
        ),
        migrations.AddField(
            model_name='injectionorder',
            name='order_status',
            field=models.CharField(choices=[('NEW', '발주'), ('CNL', '취소')], db_index=True, default='NEW', help_text='주문/취소 상태(삭제 플래그와 별개)', max_length=3, verbose_name='발주상태'),
        ),
        migrations.AddField(
            model_name='injectionorder',
            name='use_yn',
            field=models.CharField(default='Y', max_length=1, verbose_name='사용여부'),
        ),
        migrations.AddField(
            model_name='injectionorderitem',
            name='dlt_yn',
            field=models.CharField(default='N', max_length=1, verbose_name='삭제여부'),
        ),
        migrations.AlterField(
            model_name='injectionorder',
            name='dlt_yn',
            field=models.CharField(default='N', max_length=1, verbose_name='삭제여부'),
        ),
        migrations.AddIndex(
            model_name='injectionorder',
            index=models.Index(fields=['vendor', 'order_status'], name='injord_vendor_orderstatus_idx'),
        ),
        migrations.AddIndex(
            model_name='injectionorder',
            index=models.Index(fields=['flow_status'], name='injord_flowstatus_idx'),
        ),
        migrations.AddConstraint(
            model_name='injectionorder',
            constraint=models.CheckConstraint(condition=models.Q(('use_yn__in', ['Y', 'N'])), name='chk_injectionorder_use_yn_YN'),
        ),
        migrations.AddConstraint(
            model_name='injectionorder',
            constraint=models.CheckConstraint(condition=models.Q(('dlt_yn__in', ['Y', 'N'])), name='chk_injectionorder_dlt_yn_YN'),
        ),
        migrations.AddConstraint(
            model_name='injectionorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('dlt_yn__in', ['Y', 'N'])), name='chk_injectionorderitem_dlt_yn_YN'),
        ),
    ]
