# Generated by Django 5.2 on 2025-09-12 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injectionorder', '0004_remove_injectionorder_injord_vendor_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='injectionorder',
            name='flow_status',
            field=models.CharField(choices=[('NG', '미입고'), ('RDY', '입고대기'), ('PRT', '부분입고'), ('RCV', '입고완료'), ('RET', '반출')], db_index=True, default='NG', help_text='미입고/입고대기/부분입고/입고완료/반출', max_length=3, verbose_name='진행상태'),
        ),
        migrations.CreateModel(
            name='InjectionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(verbose_name='입고일')),
                ('quantity', models.PositiveIntegerField(verbose_name='입고 수량')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('dlt_yn', models.CharField(default='N', max_length=1, verbose_name='삭제여부')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='injectionorder.injectionorderitem', verbose_name='발주 품목')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='io_receipts', related_query_name='io_receipt', to='injectionorder.injectionorder', verbose_name='발주')),
            ],
            options={
                'verbose_name': '사출 발주 입고기록',
                'verbose_name_plural': '사출 발주 입고기록',
                'indexes': [models.Index(fields=['order', 'item', 'receipt_date'], name='injrcpt_ord_item_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('dlt_yn__in', ['Y', 'N'])), name='chk_injectionreceipt_dlt_yn_YN')],
            },
        ),
    ]
