# Generated by Django 5.1.7 on 2025-04-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submaterial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submaterial',
            name='delete_yn',
            field=models.CharField(choices=[('Y', '삭제'), ('N', '정상')], default='N', max_length=1, verbose_name='삭제여부'),
        ),
    ]
