# Generated by Django 5.1.7 on 2025-04-02 09:46

import django.utils.timezone
import spec.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='사양명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to=spec.models.spec_image_upload_path, verbose_name='COLOR SAMPLE')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일시')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
