# Generated by Django 5.1.7 on 2025-04-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0004_alter_vendor_outsourcing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='품명')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='별칭')),
                ('spec', models.CharField(max_length=200, verbose_name='규격')),
                ('status', models.CharField(choices=[('개발', '개발'), ('양산', '양산'), ('서비스', '서비스'), ('단종', '단종')], max_length=10, verbose_name='상태')),
                ('part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Part Number')),
                ('sub_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Part Number')),
                ('part_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Part Size')),
                ('material', models.CharField(blank=True, choices=[('ABS', 'ABS'), ('PC-ABS', 'PC-ABS')], max_length=10, null=True, verbose_name='소재')),
                ('image', models.ImageField(blank=True, null=True, upload_to='injection/images/', verbose_name='제품 이미지')),
                ('use_yn', models.CharField(choices=[('Y', '사용'), ('N', '미사용')], default='Y', max_length=1, verbose_name='사용 여부')),
                ('delete_yn', models.CharField(choices=[('N', '정상'), ('Y', '삭제')], default='N', max_length=1, verbose_name='삭제 여부')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vendor', verbose_name='사출업체')),
            ],
        ),
    ]
