# Generated by Django 5.2 on 2025-04-15 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0003_remove_moldhistory_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='단가')),
                ('date', models.DateTimeField(verbose_name='일자')),
                ('created_by', models.CharField(max_length=50, verbose_name='등록자')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('injection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='injection.injection', verbose_name='사출품')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
