# Generated by Django 5.1.7 on 2025-04-01 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=50, unique=True, verbose_name='그룹코드')),
                ('group_name', models.CharField(max_length=100, verbose_name='그룹명')),
            ],
            options={
                'verbose_name': '코드그룹',
                'verbose_name_plural': '코드그룹 목록',
                'ordering': ['group_code'],
            },
        ),
        migrations.CreateModel(
            name='CodeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='코드')),
                ('name', models.CharField(max_length=100, verbose_name='코드명')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastercode.codegroup', verbose_name='코드그룹')),
            ],
            options={
                'verbose_name': '코드상세',
                'verbose_name_plural': '코드상세 목록',
                'ordering': ['group__group_code', 'sort_order'],
                'unique_together': {('group', 'code')},
            },
        ),
    ]
