# Generated by Django 5.2 on 2025-09-12 15:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('injectionorder', '0005_alter_injectionorder_flow_status_injectionreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerShipmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_no', models.PositiveIntegerField(help_text='주문 내 순번(1..N)')),
                ('ship_date', models.DateField()),
                ('inject_date', models.DateField(blank=True, null=True)),
                ('package_count', models.PositiveIntegerField(help_text='포장(박스/대차) 개수', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_qty', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('dlt_yn', models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_shipments', to='injectionorder.injectionorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_shipment_group',
            },
        ),
        migrations.CreateModel(
            name='PartnerShipmentBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_no', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dlt_yn', models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='partnerorder.partnershipmentgroup')),
            ],
            options={
                'db_table': 'partner_shipment_box',
            },
        ),
        migrations.AddIndex(
            model_name='partnershipmentgroup',
            index=models.Index(fields=['order'], name='partner_shi_order_i_e399c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnershipmentgroup',
            constraint=models.UniqueConstraint(fields=('order', 'group_no'), name='uq_psg_order_groupno'),
        ),
        migrations.AddConstraint(
            model_name='partnershipmentgroup',
            constraint=models.CheckConstraint(condition=models.Q(('package_count__gte', 1)), name='chk_psg_pkgcnt_ge1'),
        ),
        migrations.AddConstraint(
            model_name='partnershipmentgroup',
            constraint=models.CheckConstraint(condition=models.Q(('dlt_yn__in', ['N', 'Y'])), name='chk_psg_dlt_yn'),
        ),
        migrations.AddIndex(
            model_name='partnershipmentbox',
            index=models.Index(fields=['group'], name='partner_shi_group_i_e49e3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnershipmentbox',
            constraint=models.UniqueConstraint(fields=('group', 'box_no'), name='uq_psb_group_boxno'),
        ),
        migrations.AddConstraint(
            model_name='partnershipmentbox',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', 1)), name='chk_psb_qty_ge1'),
        ),
        migrations.AddConstraint(
            model_name='partnershipmentbox',
            constraint=models.CheckConstraint(condition=models.Q(('dlt_yn__in', ['N', 'Y'])), name='chk_psb_dlt_yn'),
        ),
    ]
