# Generated by Django 5.2 on 2025-09-16 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_seq', models.PositiveIntegerField(verbose_name='하위 순번')),
                ('qty', models.PositiveIntegerField(verbose_name='수량')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='생산일')),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('dlt_yn', models.CharField(default='N', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='partnerorder.partnershipmentgroup', verbose_name='배송상세(그룹)')),
            ],
            options={
                'verbose_name': '배송 라인',
                'verbose_name_plural': '배송 라인',
                'db_table': 'partner_shipment_line',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['shipment'], name='partner_shi_shipmen_ced0ec_idx')],
                'unique_together': {('shipment', 'sub_seq')},
            },
        ),
    ]
