# Generated by Django 5.2 on 2025-08-07 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
        ('vendor', '0006_vendor_address_vendor_can_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='서경화학 임직원'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vendor', verbose_name='거래처'),
        ),
    ]
