# Generated by Django 5.2 on 2025-09-01 14:25

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('injectionorder', '0002_alter_injectionorder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(default=django.utils.timezone.now, verbose_name='수입검사일')),
                ('production_date1', models.DateField(blank=True, null=True, verbose_name='사출 생산일1')),
                ('production_qty1', models.PositiveIntegerField(blank=True, null=True, verbose_name='수량1')),
                ('production_date2', models.DateField(blank=True, null=True, verbose_name='사출 생산일2')),
                ('production_qty2', models.PositiveIntegerField(blank=True, null=True, verbose_name='수량2')),
                ('production_date3', models.DateField(blank=True, null=True, verbose_name='사출 생산일3')),
                ('production_qty3', models.PositiveIntegerField(blank=True, null=True, verbose_name='수량3')),
                ('status', models.CharField(choices=[('DRAFT', '대기'), ('PASS', '합격'), ('FAIL', '불합격'), ('HOLD', '보류')], db_index=True, default='DRAFT', max_length=8, verbose_name='합격여부')),
                ('defects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DEFECT_CD_01', 'GAS'), ('DEFECT_CD_02', '은조'), ('DEFECT_CD_03', '찍힘'), ('DEFECT_CD_04', '긁힘'), ('DEFECT_CD_05', '수축'), ('DEFECT_CD_06', 'Burr'), ('DEFECT_CD_07', '웰드'), ('DEFECT_CD_08', '미성형'), ('DEFECT_CD_09', '파손'), ('DEFECT_CD_10', '기타')], max_length=20), blank=True, default=list, size=None, verbose_name='불합격 사유코드')),
                ('inspect_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='수입검사 수량')),
                ('return_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='반출 수량')),
                ('remark', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_inspections', to='injectionorder.injectionorder', verbose_name='발주')),
            ],
            options={
                'verbose_name': '수입검사',
                'verbose_name_plural': '수입검사',
                'indexes': [models.Index(fields=['order', 'status'], name='quality_inc_order_i_4f4920_idx'), models.Index(fields=['inspection_date'], name='quality_inc_inspect_183762_idx')],
            },
        ),
    ]
