# Generated by Django 5.2 on 2025-09-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injectionorder', '0005_alter_injectionorder_flow_status_injectionreceipt'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incominginspection',
            name='shipment_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='배송상세ID'),
        ),
        migrations.AddField(
            model_name='incominginspection',
            name='shipment_seq',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='배송상세 순번'),
        ),
        migrations.AddIndex(
            model_name='incominginspection',
            index=models.Index(fields=['order', 'shipment_id', 'created_at'], name='quality_inc_order_i_a81bf6_idx'),
        ),
    ]
