# Generated by Django 5.2 on 2025-09-16 18:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerorder', '0002_partnershipmentline'),
        ('quality', '0002_incominginspection_shipment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingInspectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='검사 대상 수량')),
                ('status', models.CharField(choices=[('DRAFT', '대기'), ('PASS', '합격'), ('FAIL', '불합격'), ('HOLD', '보류')], db_index=True, default='DRAFT', max_length=8, verbose_name='합격여부')),
                ('defects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DEFECT_CD_01', 'GAS'), ('DEFECT_CD_02', '은조'), ('DEFECT_CD_03', '찍힘'), ('DEFECT_CD_04', '긁힘'), ('DEFECT_CD_05', '수축'), ('DEFECT_CD_06', 'Burr'), ('DEFECT_CD_07', '웰드'), ('DEFECT_CD_08', '미성형'), ('DEFECT_CD_09', '파손'), ('DEFECT_CD_10', '기타')], max_length=20), blank=True, default=list, size=None, verbose_name='불합격 사유코드')),
                ('return_qty', models.PositiveIntegerField(default=0, verbose_name='반출 수량')),
                ('remark', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quality.incominginspection', verbose_name='수입검사 헤더')),
                ('shipment_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_details', to='partnerorder.partnershipmentline', verbose_name='배송 라인')),
            ],
            options={
                'verbose_name': '수입검사 라인',
                'verbose_name_plural': '수입검사 라인',
                'indexes': [models.Index(fields=['inspection'], name='quality_inc_inspect_dd71aa_idx'), models.Index(fields=['shipment_line'], name='quality_inc_shipmen_5cf66a_idx'), models.Index(fields=['status'], name='quality_inc_status_ad7fd6_idx')],
                'unique_together': {('inspection', 'shipment_line')},
            },
        ),
    ]
