# Generated by Django 5.2 on 2025-11-19 12:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_nonferrousaddition_nonferrousadditionline'),
        ('quality', '0003_incominginspectiondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(default=django.utils.timezone.now, verbose_name='출하검사일')),
                ('inspect_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='검사수량')),
                ('good_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='양품수량')),
                ('defect_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='불량수량')),
                ('loss_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='LOSS 수량')),
                ('status', models.CharField(choices=[('DRAFT', '대기'), ('PASS', '합격'), ('FAIL', '불합격'), ('HOLD', '보류')], db_index=True, default='DRAFT', max_length=8, verbose_name='합격여부')),
                ('remark', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workorder', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_inspection', to='production.workorder', verbose_name='작업 LOT')),
            ],
            options={
                'verbose_name': '출하검사',
                'verbose_name_plural': '출하검사',
            },
        ),
        migrations.CreateModel(
            name='OutgoingInspectionDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PL_STAIN', '얼룩'), ('PL_UNPLATED', '미도금'), ('PL_SPOT_UNPLATED', '점미도금'), ('PL_NO_CHROME', '미크롬'), ('PL_COLOR_GLOSS', '색상광택'), ('PL_BLISTER', '부풀음'), ('PL_PIT', '피트'), ('PL_FOREIGN', '불순물'), ('PL_FOREIGN_ORG', '불순물유기'), ('PL_BURNING', '도금탐'), ('PL_DENT', '찍힘'), ('PL_SCRATCH', '긁힘'), ('PL_BUILDUP', '도금뭉침'), ('PL_HANDLING', '취급'), ('PL_PROCESS', '공정'), ('PL_CRACK', '크랙'), ('PL_STRIPE_PIT', '줄피트/면커버'), ('PL_OTHER', '기타(도금불량)'), ('IN_GAS', 'GAS'), ('IN_SILVER', '은조'), ('IN_DENT', '찍힘'), ('IN_SCRATCH', '긁힘'), ('IN_SHRINK', '수축'), ('IN_BURR', 'Burr'), ('IN_WELD', '웰드'), ('IN_OTHER', '기타(사출불량)')], max_length=32, verbose_name='불량 코드')),
                ('qty', models.PositiveIntegerField(verbose_name='불량 수량')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='quality.outgoinginspection', verbose_name='출하검사')),
            ],
            options={
                'verbose_name': '출하검사 불량',
                'verbose_name_plural': '출하검사 불량',
            },
        ),
        migrations.AddIndex(
            model_name='outgoinginspection',
            index=models.Index(fields=['inspection_date'], name='quality_out_inspect_1f8868_idx'),
        ),
        migrations.AddIndex(
            model_name='outgoinginspection',
            index=models.Index(fields=['status'], name='quality_out_status_ca1430_idx'),
        ),
        migrations.AddIndex(
            model_name='outgoinginspectiondefect',
            index=models.Index(fields=['inspection'], name='quality_out_inspect_e1227a_idx'),
        ),
        migrations.AddIndex(
            model_name='outgoinginspectiondefect',
            index=models.Index(fields=['code'], name='quality_out_code_5a35b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='outgoinginspectiondefect',
            unique_together={('inspection', 'code')},
        ),
    ]
