# Generated by Django 5.2 on 2025-11-20 12:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_outgoinginspection_outgoinginspectiondefect_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingFinishedLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_lot', models.CharField(help_text='예: C-YYYYMMDD-01 형식의 LOT 번호', max_length=32, unique=True, verbose_name='완성 LOT')),
                ('box_size', models.PositiveIntegerField(default=0, help_text='해당 BOX에 포장된 수량 (EA 단위)', verbose_name='박스당 수량')),
                ('produced_at', models.DateTimeField(blank=True, help_text='연결된 작업 LOT의 실제 생산 완료 시각 (옵션)', null=True, verbose_name='생산일시')),
                ('inspected_at', models.DateTimeField(blank=True, null=True, verbose_name='검사일시')),
                ('packed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='포장일시')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_lots', to='quality.outgoinginspection', verbose_name='출하검사')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_finished_lots', to=settings.AUTH_USER_MODEL, verbose_name='작업자')),
            ],
            options={
                'verbose_name': '출하완성 LOT',
                'verbose_name_plural': '출하완성 LOT',
                'indexes': [models.Index(fields=['inspection'], name='quality_out_inspect_730088_idx'), models.Index(fields=['finished_lot'], name='quality_out_finishe_5af1b6_idx')],
            },
        ),
    ]
