# Generated by Django 5.2 on 2025-11-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_outgoingfinishedlot'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoinginspection',
            name='adjust_qty',
            field=models.IntegerField(default=0, help_text='계획수량(WorkOrder.order_qty) 대비 실제 실물 수량 증감', verbose_name='실수량 조정수량(±EA)'),
        ),
        migrations.AddField(
            model_name='outgoinginspection',
            name='adjust_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='실수량 조정 사유'),
        ),
        migrations.AddField(
            model_name='outgoinginspection',
            name='hold_qty',
            field=models.PositiveIntegerField(blank=True, help_text='HOLD 상태로 다음 검사로 넘기는 양품 잔여 수량', null=True, verbose_name='잔량수량'),
        ),
        migrations.AddField(
            model_name='outgoinginspection',
            name='result',
            field=models.CharField(choices=[('NONE', '미결정'), ('PASS', '합격'), ('FAIL', '불합격')], default='NONE', max_length=8, verbose_name='검사 결과'),
        ),
        migrations.AlterField(
            model_name='outgoinginspection',
            name='status',
            field=models.CharField(choices=[('DRAFT', '대기'), ('DONE', '완료'), ('HOLD', '보류/잔량')], db_index=True, default='DRAFT', max_length=8, verbose_name='검사 상태'),
        ),
    ]
