# Generated by Django 5.2 on 2025-11-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_outgoinginspection_adjust_qty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outgoingfinishedlot',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='outgoingfinishedlot',
            name='quality_out_inspect_730088_idx',
        ),
        migrations.RemoveIndex(
            model_name='outgoingfinishedlot',
            name='quality_out_finishe_5af1b6_idx',
        ),
        migrations.RemoveField(
            model_name='outgoingfinishedlot',
            name='inspected_at',
        ),
        migrations.RemoveField(
            model_name='outgoingfinishedlot',
            name='produced_at',
        ),
        migrations.AddField(
            model_name='outgoingfinishedlot',
            name='shipped',
            field=models.BooleanField(default=False, verbose_name='출하여부'),
        ),
        migrations.AddField(
            model_name='outgoingfinishedlot',
            name='status',
            field=models.CharField(choices=[('FULL', '완성'), ('SHORT', '부족')], default='FULL', max_length=10, verbose_name='포장상태'),
        ),
        migrations.AlterField(
            model_name='outgoingfinishedlot',
            name='box_size',
            field=models.PositiveIntegerField(default=0, verbose_name='박스 수량'),
        ),
        migrations.AlterField(
            model_name='outgoingfinishedlot',
            name='finished_lot',
            field=models.CharField(max_length=30, verbose_name='완성 LOT 번호'),
        ),
        migrations.AlterField(
            model_name='outgoingfinishedlot',
            name='operator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='작업자'),
        ),
        migrations.AlterField(
            model_name='outgoingfinishedlot',
            name='packed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='포장일시'),
        ),
    ]
