# Generated by Django 5.2 on 2025-12-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0007_alter_outgoingfinishedlot_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='outgoingfinishedlot',
            constraint=models.UniqueConstraint(fields=('finished_lot',), name='uq_outgoingfinishedlot_finished_lot'),
        ),
    ]
