# Generated by Django 5.2 on 2025-12-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0008_outgoingfinishedlot_uq_outgoingfinishedlot_finished_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingfinishedlot',
            name='dlt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제일시'),
        ),
        migrations.AddField(
            model_name='outgoingfinishedlot',
            name='dlt_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='삭제사유'),
        ),
        migrations.AddField(
            model_name='outgoingfinishedlot',
            name='dlt_user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='삭제자'),
        ),
        migrations.AddField(
            model_name='outgoingfinishedlot',
            name='dlt_yn',
            field=models.CharField(default='N', max_length=1, verbose_name='삭제여부'),
        ),
    ]
