# Generated by Django 5.2 on 2025-12-04 09:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_packaging_spec_file_and_more'),
        ('quality', '0009_outgoingfinishedlot_dlt_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(db_index=True, help_text='C-YYYYMMDD-XX 형식의 고유 LOT 번호', max_length=30, unique=True, verbose_name='완성 LOT 번호')),
                ('box_size', models.PositiveIntegerField(help_text='FULL 로 인정되는 기준 수량', verbose_name='기준 박스 수량(EA)')),
                ('qty', models.PositiveIntegerField(default=0, help_text='현재 BOX 안에 들어 있는 수량', verbose_name='현재 수량(EA)')),
                ('status', models.CharField(choices=[('FULL', '완성'), ('SHORT', '부족')], db_index=True, default='SHORT', max_length=10, verbose_name='포장상태')),
                ('shipped', models.BooleanField(db_index=True, default=False, verbose_name='출하 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dlt_yn', models.CharField(default='N', max_length=1, verbose_name='삭제여부')),
                ('dlt_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('dlt_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='삭제자')),
                ('dlt_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='삭제사유')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_boxes', to='product.product', verbose_name='품목')),
            ],
            options={
                'verbose_name': '완성 BOX',
                'verbose_name_plural': '완성 BOX',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FinishedBoxFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_added', models.PositiveIntegerField(help_text='해당 출하검사에서 이 BOX 에 적재된 수량', verbose_name='투입 수량(EA)')),
                ('filled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='투입 일시')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='작업자')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='quality.finishedbox', verbose_name='완성 BOX')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_fills', to='quality.outgoinginspection', verbose_name='출하검사')),
            ],
            options={
                'verbose_name': '완성 BOX 적재 이력',
                'verbose_name_plural': '완성 BOX 적재 이력',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='finishedbox',
            index=models.Index(fields=['product'], name='quality_fin_product_6a6356_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedbox',
            index=models.Index(fields=['status'], name='quality_fin_status_f22f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedbox',
            index=models.Index(fields=['shipped'], name='quality_fin_shipped_a09cc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='finishedbox',
            constraint=models.UniqueConstraint(fields=('lot_no',), name='uq_finishedbox_lot_no'),
        ),
        migrations.AddIndex(
            model_name='finishedboxfill',
            index=models.Index(fields=['box'], name='quality_fin_box_id_2b97b9_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedboxfill',
            index=models.Index(fields=['inspection'], name='quality_fin_inspect_feeb4b_idx'),
        ),
    ]
