# Generated by Django 5.2 on 2025-12-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0010_finishedbox_finishedboxfill_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outgoingfinishedlot',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='outgoingfinishedlot',
            name='uq_outgoingfinishedlot_finished_lot',
        ),
    ]
