# Generated by Django 5.2 on 2025-07-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RackMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_master_id', models.CharField(max_length=30, unique=True)),
                ('product_nm', models.CharField(max_length=100)),
                ('product_no', models.CharField(max_length=100)),
                ('make_comp', models.CharField(max_length=100)),
                ('con_num', models.IntegerField(default=0)),
                ('max_count', models.IntegerField(default=0)),
                ('use_yn', models.CharField(default='Y', max_length=1)),
                ('dlt_yn', models.CharField(default='N', max_length=1)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
