# Generated by Django 5.2 on 2025-07-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rackmaster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rack/images/'),
        ),
        migrations.AlterField(
            model_name='rackmaster',
            name='con_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rackmaster',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rackmaster',
            name='dlt_yn',
            field=models.CharField(choices=[('N', '정상'), ('Y', '삭제')], max_length=1),
        ),
        migrations.AlterField(
            model_name='rackmaster',
            name='max_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rackmaster',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rackmaster',
            name='rack_master_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rackmaster',
            name='use_yn',
            field=models.CharField(choices=[('Y', '사용'), ('N', '미사용')], max_length=1),
        ),
    ]
