# Generated by Django 5.2 on 2025-04-22 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_productprice'),
        ('vendor', '0005_alter_vendor_outsourcing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='수주일자')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('use_yn', models.CharField(choices=[('Y', '사용'), ('N', '미사용')], default='Y', max_length=1, verbose_name='사용여부')),
                ('delete_yn', models.CharField(choices=[('Y', '삭제'), ('N', '정상')], default='N', max_length=1, verbose_name='삭제여부')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='생성자')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='수정자')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor', verbose_name='고객사')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('delivery_date', models.DateField(verbose_name='출하예정일')),
                ('shipped_date', models.DateField(blank=True, null=True, verbose_name='출고일')),
                ('status', models.CharField(choices=[('등록', '등록'), ('지연', '지연'), ('부분출고', '부분출고'), ('출고', '출고')], default='등록', max_length=20, verbose_name='출하상태')),
                ('unit_price', models.PositiveIntegerField(default=0, verbose_name='단가')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='합계금액')),
                ('use_yn', models.CharField(choices=[('Y', '사용'), ('N', '미사용')], default='Y', max_length=1, verbose_name='사용여부')),
                ('delete_yn', models.CharField(choices=[('Y', '삭제'), ('N', '정상')], default='N', max_length=1, verbose_name='삭제여부')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='생성자')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='수정자')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.customerorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='제품')),
            ],
        ),
    ]
