# Generated by Django 5.2 on 2025-04-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderitem',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice No'),
        ),
    ]
