# Generated by Django 5.2 on 2025-12-10 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_packaging_spec_file_and_more'),
        ('quality', '0011_alter_outgoingfinishedlot_options_and_more'),
        ('sales', '0002_customerorderitem_invoice_number'),
        ('vendor', '0007_vendoritemkind_vendor_major_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh_lot', models.CharField(max_length=20, unique=True, verbose_name='출하 LOT')),
                ('ship_date', models.DateField(default=django.utils.timezone.now, verbose_name='출하일')),
                ('status', models.CharField(choices=[('DRAFT', '임시저장'), ('CONFIRMED', '출하확정'), ('CANCELLED', '취소')], default='CONFIRMED', max_length=20, verbose_name='상태')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('use_yn', models.CharField(choices=[('Y', '사용'), ('N', '미사용')], default='Y', max_length=1, verbose_name='사용여부')),
                ('delete_yn', models.CharField(choices=[('Y', '삭제'), ('N', '정상')], default='N', max_length=1, verbose_name='삭제여부')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='생성자')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='수정자')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendor.vendor', verbose_name='출하처')),
            ],
        ),
        migrations.CreateModel(
            name='SalesShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_lot', models.CharField(max_length=30, verbose_name='완성 LOT')),
                ('quantity', models.PositiveIntegerField(verbose_name='출하수량')),
                ('unit_price', models.PositiveIntegerField(default=0, verbose_name='단가')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='금액')),
                ('use_yn', models.CharField(choices=[('Y', '사용'), ('N', '미사용')], default='Y', max_length=1, verbose_name='사용여부')),
                ('delete_yn', models.CharField(choices=[('Y', '삭제'), ('N', '정상')], default='N', max_length=1, verbose_name='삭제여부')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='생성자')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='수정자')),
                ('finished_box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.finishedbox', verbose_name='완성 LOT 박스')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='제품')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesshipment', verbose_name='출하서')),
            ],
        ),
        migrations.CreateModel(
            name='SalesShipmentOrderMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_qty', models.PositiveIntegerField(verbose_name='매칭수량')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='생성자')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_maps', to='sales.customerorderitem', verbose_name='수주라인')),
                ('shipment_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_maps', to='sales.salesshipmentline', verbose_name='출하라인')),
            ],
        ),
    ]
