# Generated by Django 5.2 on 2025-12-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesshipment_salesshipmentline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesshipment',
            name='operator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='출고자'),
        ),
        migrations.AddField(
            model_name='salesshipment',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='품명'),
        ),
        migrations.AddField(
            model_name='salesshipment',
            name='program',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='프로그램'),
        ),
        migrations.AddField(
            model_name='salesshipment',
            name='total_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='총 출하수량'),
        ),
    ]
