# Generated by Django 5.1.7 on 2025-04-03 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0004_alter_vendor_outsourcing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='품명')),
                ('spec', models.CharField(blank=True, max_length=100, null=True, verbose_name='규격')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chemical/images/', verbose_name='제품 이미지')),
                ('use_yn', models.CharField(choices=[('Y', '사용'), ('N', '미사용')], default='Y', max_length=1, verbose_name='사용여부')),
                ('delete_yn', models.CharField(choices=[('N', '정상'), ('Y', '삭제')], default='N', max_length=1, verbose_name='삭제여부')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='등록자')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='수정자')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vendor', verbose_name='고객사')),
            ],
        ),
    ]
