# Generated by Django 5.1.7 on 2025-04-03 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='단가')),
                ('date', models.DateTimeField(verbose_name='일자')),
                ('created_by', models.CharField(max_length=50, verbose_name='등록자')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='chemical.chemical', verbose_name='약품')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
