# Generated by Django 5.2 on 2025-10-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0002_chemicalprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemical',
            options={'verbose_name': '약품', 'verbose_name_plural': '약품'},
        ),
        migrations.AlterModelOptions(
            name='chemicalprice',
            options={'ordering': ['-date'], 'verbose_name': '약품 단가', 'verbose_name_plural': '약품 단가'},
        ),
        migrations.AddField(
            model_name='chemical',
            name='container_uom',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='포장단위(말/통/드럼/EA 등)'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='spec_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='규격 비고(성상/등급)'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='spec_unit',
            field=models.CharField(blank=True, choices=[('PCT', '%'), ('KG', 'kg'), ('G', 'g'), ('L', 'L'), ('ML', 'mL'), ('MM', 'mm'), ('CM', 'cm'), ('M', 'm'), ('EA', 'EA')], max_length=10, null=True, verbose_name='측정 단위'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='unit_qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='단위규격(정수)'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='spec',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='규격(자연어)'),
        ),
    ]
