# Generated by Django 5.2 on 2025-11-12 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0003_add_spec_fields_and_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='msds_file',
            field=models.FileField(blank=True, null=True, upload_to='chemical/msds/', verbose_name='MSDS 파일'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='tds_file',
            field=models.FileField(blank=True, null=True, upload_to='chemical/tds/', verbose_name='TDS 파일'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='use_base_qty',
            field=models.PositiveIntegerField(blank=True, help_text='예) 4L, 사용단위 mL → 4000', null=True, verbose_name='포장당 사용단위 수량'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='use_unit',
            field=models.CharField(blank=True, choices=[('PCT', '%'), ('KG', 'kg'), ('G', 'g'), ('L', 'L'), ('ML', 'mL'), ('MM', 'mm'), ('CM', 'cm'), ('M', 'm'), ('EA', 'EA')], max_length=10, null=True, verbose_name='사용 단위'),
        ),
        migrations.CreateModel(
            name='ChemicalControlRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='관리 하한')),
                ('upper_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='관리 상한')),
                ('avg_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='관리 평균')),
                ('unit', models.CharField(choices=[('G_L', 'g/L'), ('ML_L', 'ml/L')], max_length=10, verbose_name='단위')),
                ('date', models.DateTimeField(verbose_name='일자')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='변동사유')),
                ('created_by', models.CharField(max_length=50, verbose_name='등록자')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_ranges', to='chemical.chemical', verbose_name='약품')),
            ],
            options={
                'verbose_name': '관리범위',
                'verbose_name_plural': '관리범위',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ChemicalStdConcentration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='표준농도')),
                ('unit', models.CharField(choices=[('G_L', 'g/L'), ('ML_L', 'ml/L')], max_length=10, verbose_name='단위')),
                ('date', models.DateTimeField(verbose_name='일자')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='변동사유')),
                ('created_by', models.CharField(max_length=50, verbose_name='등록자')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_concentrations', to='chemical.chemical', verbose_name='약품')),
            ],
            options={
                'verbose_name': '표준농도',
                'verbose_name_plural': '표준농도',
                'ordering': ['-date'],
            },
        ),
    ]
